"""
Gradle Tool - Generates Gradle build configuration files

This tool creates build.gradle, settings.gradle, gradle.properties, and LICENSE files.
"""
from pathlib import Path
from typing import Dict, Any

from config import (
    MINECRAFT_VERSION,
    FABRIC_LOADER_VERSION,
    FABRIC_API_VERSION,
    YARN_MAPPINGS,
)


def generate_gradle_files(
    workspace_path: Path,
    mod_id: str,
    mod_name: str,
    version: str = "1.0.0",
    minecraft_version: str = None,
    dependencies: Dict[str, str] = None
) -> Dict[str, Any]:
    """
    Generate Gradle build configuration files

    Args:
        workspace_path: Mod directory path
        mod_id: Mod identifier
        mod_name: Human-readable mod name
        version: Mod version
        minecraft_version: Minecraft version (defaults to config value)
        dependencies: Additional dependencies dict

    Returns:
        Dictionary with paths to generated files
    """
    mod_dir = Path(workspace_path)
    mc_version = minecraft_version or MINECRAFT_VERSION
    maven_group = f"com.example.{mod_id.replace('-', '')}"
    archives_base_name = mod_id

    # gradle.properties
    gradle_props = f"""# Fabric Properties
minecraft_version={mc_version}
yarn_mappings={YARN_MAPPINGS}
loader_version={FABRIC_LOADER_VERSION}

# Mod Properties
mod_version={version}
maven_group={maven_group}
archives_base_name={archives_base_name}

# Dependencies
fabric_version={FABRIC_API_VERSION}

# Build Configuration
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
"""
    gradle_props_path = mod_dir / "gradle.properties"
    gradle_props_path.write_text(gradle_props)

    # build.gradle
    build_gradle = """plugins {
\tid 'fabric-loom' version '1.6-SNAPSHOT'
\tid 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
\tmavenCentral()
}

dependencies {
\tminecraft "com.mojang:minecraft:${project.minecraft_version}"
\tmappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
\tmodImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
\tmodImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

loom {
\tsplitEnvironmentSourceSets()
}

processResources {
\tinputs.property "version", project.version
\tfilteringCharset "UTF-8"

\tfilesMatching("fabric.mod.json") {
\t\texpand "version": project.version
\t}
}

java {
\tsourceCompatibility = JavaVersion.VERSION_21
\ttargetCompatibility = JavaVersion.VERSION_21
\twithSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
\tit.options.release = 21
}

jar {
\tfrom("LICENSE") {
\t\trename { "${it}_${project.archives_base_name}"}
\t}
}
"""
    build_gradle_path = mod_dir / "build.gradle"
    build_gradle_path.write_text(build_gradle)

    # settings.gradle
    settings_gradle = """pluginManagement {
\trepositories {
\t\tmaven {
\t\t\tname = 'Fabric'
\t\t\turl = 'https://maven.fabricmc.net/'
\t\t}
\t\tmavenCentral()
\t\tgradlePluginPortal()
\t}
}
"""
    settings_gradle_path = mod_dir / "settings.gradle"
    settings_gradle_path.write_text(settings_gradle)

    # LICENSE
    license_path = mod_dir / "LICENSE"
    license_path.write_text("MIT License\n\nGenerated by AI Mod Generator")

    return {
        "status": "success",
        "build_gradle_path": str(build_gradle_path),
        "settings_gradle_path": str(settings_gradle_path),
        "gradle_properties_path": str(gradle_props_path),
        "license_path": str(license_path)
    }


__all__ = ["generate_gradle_files"]
